version: '3.8'

services: 
  recipe-api:
    restart: always
    environment:
      PRODUCTION: 'true'

  recipe-web:
    restart: always
    environment:
      PRODUCTION: 'true'

  redis:
    restart: always
    environment:
      TTL: "3600"
      
  mongodb:
    restart: always
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

volumes:
  dbdata:

