version: '3.8'

services: 
  recipe-api:
    image: 2467100/recipe-api:latest
    environment:
      MONGODB_URI: mongodb://vit:secret@mongodb:27017/rcp
      REDIS_URI: redis://redis:6379
    networks:
      - recipe_net
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
      - redis
  
  mongodb:
    image: 2467100/recipe-surf-db
    container_name: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: vit
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: rcp
    networks:
      - recipe_net
    ports:
      - "27017:27017"
  
  recipe-web:
    image: 2467100/recipe-web:latest
    ports: 
      - "80:80"
    networks:
      - recipe_net
    depends_on:
      - recipe-api

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    networks:
      - recipe_net

networks:
  recipe_net: